// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDilazP-NfqVpgKBaizw-La03ZViGYFrlI',
    appId: '1:309606259473:web:34f00336f9f9a9fe9fcab0',
    messagingSenderId: '309606259473',
    projectId: 'group2-charting',
    authDomain: 'group2-charting.firebaseapp.com',
    storageBucket: 'group2-charting.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7SwBWMLJCt24hvewDOmiKAUrbApcD4OI',
    appId: '1:309606259473:android:211ca1dfb92d03c29fcab0',
    messagingSenderId: '309606259473',
    projectId: 'group2-charting',
    storageBucket: 'group2-charting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKBMqMr2aHzDBLSEA9SMjqrS5-JsGkgUo',
    appId: '1:309606259473:ios:858a3cda72bea0fd9fcab0',
    messagingSenderId: '309606259473',
    projectId: 'group2-charting',
    storageBucket: 'group2-charting.firebasestorage.app',
    iosBundleId: 'com.example.group2Chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKBMqMr2aHzDBLSEA9SMjqrS5-JsGkgUo',
    appId: '1:309606259473:ios:858a3cda72bea0fd9fcab0',
    messagingSenderId: '309606259473',
    projectId: 'group2-charting',
    storageBucket: 'group2-charting.firebasestorage.app',
    iosBundleId: 'com.example.group2Chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDilazP-NfqVpgKBaizw-La03ZViGYFrlI',
    appId: '1:309606259473:web:4f7a05ca724001e69fcab0',
    messagingSenderId: '309606259473',
    projectId: 'group2-charting',
    authDomain: 'group2-charting.firebaseapp.com',
    storageBucket: 'group2-charting.firebasestorage.app',
  );
}
